apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: fintech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: 608420805829.dkr.ecr.us-east-1.amazonaws.com/fintech/auth-service:918ad3c2628f09977c6e4ee40d156958c0ffcfa3
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "300m"
          envFrom:
            - configMapRef:
                name: fintech-config
            - secretRef:
                name: fintech-secret

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: fintech
spec:
  selector:
    app: auth-service
  ports:
    - port: 8081
      targetPort: 8081