apiVersion: v1
kind: Secret
metadata:
  name: fintech-secret
  namespace: fintech
type: Opaque
stringData:
  DB_USER: postgres
  DB_PASS: postgres
  JWT_SECRET: supersecretkeyprojectfera0903200414032026