name: CI/CD - Fintech

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 608420805829.dkr.ecr.us-east-1.amazonaws.com
  CLUSTER_NAME: scrumptious-classical-crow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - service: gateway
            image: api-gateway
            deployment: api-gateway

          - service: AuthService
            image: auth-service
            deployment: auth-service

          - service: AccountService
            image: account-service
            deployment: account-service

          - service: transferService
            image: transfer-service
            deployment: transfer-service

          - service: notificationService
            image: notification-service
            deployment: notification-service

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login no ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build
        run: |
          docker build -t $ECR_REGISTRY/fintech/${{ matrix.image }}:${{ github.sha }} ./${{ matrix.service }}

      - name: Push
        run: |
          docker push $ECR_REGISTRY/fintech/${{ matrix.image }}:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Conectar no EKS
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

      - name: Criar base (namespace + config)
        run: |
          kubectl apply -f k8s/namespace.yml
          kubectl apply -f k8s/configmap.yml

      - name: Criar infraestrutura
        run: |
          kubectl apply -f k8s/kafka-deployment.yml -n fintech
          kubectl apply -f k8s/postgres-deployment.yml -n fintech
          kubectl apply -f k8s/redis-deployment.yml -n fintech

      - name: Aguardar infra
        run: |
          kubectl rollout status deployment/postgres -n fintech
          kubectl rollout status deployment/kafka -n fintech
          kubectl rollout status deployment/redis -n fintech
          
          echo "Aguardando serviços estabilizarem..."
          sleep 20

      - name: Criar observabilidade
        run: |
          kubectl apply -f prometheus-configmap.yml -n fintech
          kubectl apply -f prometheus-deployment.yml -n fintech
          kubectl apply -f prometheus-service.yml -n fintech
          kubectl apply -f grafana-deployment.yml -n fintech
          kubectl apply -f grafana-service.yml -n fintech

      - name: Aguardar observabilidade
        run: |
          kubectl rollout status deployment/prometheus -n fintech
          kubectl rollout status deployment/grafana -n fintech

      - name: Criar deployments
        run: |
          kubectl apply -f k8s/auth-deployment.yml -n fintech
          kubectl apply -f k8s/account-deployment.yml -n fintech
          kubectl apply -f k8s/transfer-deployment.yml -n fintech
          kubectl apply -f k8s/notification-deployment.yml -n fintech
          kubectl apply -f k8s/gateway-deployment.yml -n fintech

      - name: Atualizar imagens
        run: |
          kubectl set image deployment/auth-service auth-service=$ECR_REGISTRY/fintech/auth-service:${{ github.sha }} -n fintech
          kubectl set image deployment/account-service account-service=$ECR_REGISTRY/fintech/account-service:${{ github.sha }} -n fintech
          kubectl set image deployment/transfer-service transfer-service=$ECR_REGISTRY/fintech/transfer-service:${{ github.sha }} -n fintech
          kubectl set image deployment/notification-service notification-service=$ECR_REGISTRY/fintech/notification-service:${{ github.sha }} -n fintech
          kubectl set image deployment/api-gateway api-gateway=$ECR_REGISTRY/fintech/api-gateway:${{ github.sha }} -n fintech